routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('change-language');

Auth::routes(['register' => false, 'verify' => false]);

Route::group(['middleware' => 'localization'], function () {
    Route::prefix('')->group(function () {
        Route::get('/', [
            'as' => 'user_check.index',
            'uses' => 'UserCheckController@index',
        ]);
        Route::post('/checkin', [
            'as' => 'user_check.checkin',
            'uses' => 'UserCheckController@checkin',
        ]);
        Route::post('/checkout', [
            'as' => 'user_check.checkout',
            'uses' => 'UserCheckController@checkout',
        ]);
        Route::post('/notify', [
            'as' => 'notify.send',
            'uses' => 'NotificationController@index',
        ]);
        Route::get('/person', [
            'as' => 'person.personList',
            'uses' => 'ListCheckController@personList',
        ]);
        Route::get('/addProblem', [
            'as' => 'person.addProblem',
            'uses' => 'ListCheckController@addProblem',
        ]);
        Route::post('/storeProblem', [
            'as' => 'person.storeProblem',
            'uses' => 'ListCheckController@storeProblem',
        ]);
        Route::get('/people', [
            'as' => 'people.peopleList',
            'uses' => 'ListCheckController@peopleList',
        ]);
        Route::get('/updateCheckOut/{id}', [
            'as' => 'people.updateCheckOut',
            'uses' => 'ListCheckController@updateCheckOut',
        ]);
        Route::get('/updateCheckOut/{id}', [
            'as' => 'people.updateCheckOut',
            'uses' => 'ListCheckController@updateCheckOut',
        ]);
        Route::get('/viewCheck', [
            'as' => 'people.viewCheck',
            'uses' => 'ListCheckController@viewCheck',
        ]);
        Route::post('/storeCheck', [
            'as' => 'people.storeCheck',
            'uses' => 'ListCheckController@storeCheck',
        ]);
    });

    Route::prefix('/statistic')->group(function () {
        Route::get('/', [
            'as' => 'statistic.index',
            'uses' => 'StatisticController@index',
        ]);
        Route::get('/view/{id}/{year}/{month}', [
            'as' => 'statistic.view',
            'uses' => 'StatisticController@view',
        ]);
        Route::post('getMonth/{year}', [
            'as' => 'statistic.getMonth',
            'uses' => 'StatisticController@getMonth',
        ]);
        Route::post('getData/{year}/{month}', [
            'as' => 'statistic.getData',
            'uses' => 'StatisticController@getData',
        ]);
    });

    Route::prefix('/users')->group(function () {
        Route::get('/', [
            'as' => 'users.index',
            'uses' => 'UserController@index',
            'middleware' => 'can:user-view'
        ]);
        Route::get('/add', [
            'as' => 'users.add',
            'uses' => 'UserController@add',
            'middleware' => 'can:user-create'
        ]);
        Route::post('/create', [
            'as' => 'users.create',
            'uses' => 'UserController@create',
            'middleware' => 'can:user-create'
        ]);
        Route::get('/edit/{id}', [
            'as' => 'users.edit',
            'uses' => 'UserController@edit',
            'middleware' => 'can:user-update'
        ]);
        Route::post('/update/{id}', [
            'as' => 'users.update',
            'uses' => 'UserController@update',
            'middleware' => 'can:user-update'
        ]);
        Route::post('/delete/{id}', [
            'as' => 'users.delete',
            'uses' => 'UserController@delete',
            'middleware' => 'can:user-delete'
        ]);
        Route::get('/info', [
            'as' => 'users.info',
            'uses' => 'UserController@info',
        ]);
        Route::get('/editInfo/{id}', [
            'as' => 'users.editInfo',
            'uses' => 'UserController@editInfo',
        ]);
        Route::post('/updateInfo/{id}', [
            'as' => 'users.updateInfo',
            'uses' => 'UserController@updateInfo',
        ]);
    });

    Route::resource('leave_requests', 'LeaveRequestController')->only([
        'index', 'create', 'store',
    ]);
    Route::get('change-password', 'Auth\ChangePasswordController@index');
    Route::post('change-password', 'Auth\ChangePasswordController@store')->name('change.password');
    Route::post('leave_requests/deny/{id}', 'LeaveRequestController@deny')->name('leave_requests.deny');
    Route::get('leave_requests/accept/{id}', 'LeaveRequestController@accept')->name('leave_requests.accept');
    Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('change-language');
});

app/LeaveRequest.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class LeaveRequest extends Model
{
    use SoftDeletes;
    protected $guarded =[];

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo('App\User', 'user_id', 'id')->withTrashed();
    }

    public function getDayTwoDay()
    {
        $start = Carbon::parse($this->start_at);
        $end = Carbon::parse($this->end_at);
        return number_format($start->diffInHours($end)/24,2);
    }
}

app/Http/Controllers/LeaveRequestController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DenyRequest;
use App\Http\Requests\LeaveRequest;
use App\Mail\LeaveRequestAdminMail;
use App\Mail\LeaveRequestMail;
use App\Notifications\LeaveRequestNotification;
use App\Repositories\LeaveRequests\LeaveRequestRepositoryInterface;
use App\Repositories\Users\UserRepositoryInterface;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Symfony\Component\HttpFoundation\Response;
use RealRashid\SweetAlert\Facades\Alert;

class LeaveRequestController extends Controller
{
    protected $leaveRequestEloquent;
    protected $userRepository;

    public function __construct(LeaveRequestRepositoryInterface $leaveRequestEloquent, UserRepositoryInterface $userRepository)
    {
        $this->middleware(['auth']);
        $this->leaveRequestEloquent = $leaveRequestEloquent;
        $this->userRepository = $userRepository;
    }

    public function index()
    {
        abort_if(Gate::denies('leave-index'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $leave_requests = $this->leaveRequestEloquent->getAll();
        $leave_requestPersons = $this->leaveRequestEloquent->getListLeaveRequestPerson();
        return view('timesheet_management.leave_requests.index', compact('leave_requests','leave_requestPersons'));
    }

    public function create()
    {
        abort_if(Gate::denies('leave-create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $user = Auth::user();
        return view('timesheet_management.leave_requests.add', compact('user'));
    }

    public function store(LeaveRequest $request)
    {
        abort_if(Gate::denies('leave-store'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        try {
            $request = (object)$request->validated();
            $this->leaveRequestEloquent->create($this->leaveRequestEloquent->insertDataLeaveRequest($request));
            // send notification
            $users = $this->userRepository->getListAdminUser();
            $data = [
                'title' => 'Yêu cầu xin nghỉ',
                'content' => $request->content,
                'name' => $this->userRepository->getNameUser(),
            ];
            foreach ($users as $user) {
                $user->notify(new LeaveRequestNotification($data));
                Mail::to($user->email)->send(new LeaveRequestAdminMail($data));
            }
            Alert::success('Success', 'Send Request success.Please forward admin approved')->autoClose(10000);
            return redirect()->route('leave_requests.index');
        } catch (\Exception $exception) {
            Log::error('Message: ' . $exception->getMessage() . 'Line : ' . $exception->getLine());
            return back()->with('error', "Send Request failed");
        }
    }

    public function accept($id)
    {
        abort_if(Gate::denies('leave-accept'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $this->leaveRequestEloquent->update($id, ['status' => 'approved']);
        $userId = $this->leaveRequestEloquent->getListLeaveRequestPersonId($id);
        $user = $this->userRepository->getUser($userId);

        $data = [
            'title' => 'Yêu cầu xin nghỉ ',
            'content' => 'Yêu cầu xin nghỉ của bạn đã được chấp nhận',
        ];
        $user->notify(new LeaveRequestNotification($data));
        Mail::to($user->email)->send(new LeaveRequestMail($data));
        Alert::success('Success', 'Request is approved. Notification and email send to user')->autoClose(3000);
        return redirect()->route('leave_requests.index');
    }

    public function deny($id, DenyRequest $request): \Illuminate\Http\RedirectResponse
    {
        abort_if(Gate::denies('leave-deny'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $request = (object)$request->validated();
        $userId = $this->leaveRequestEloquent->getListLeaveRequestPersonId($id);
        $user = $this->userRepository->getUser($userId);
        $this->leaveRequestEloquent->update($id, ['status' => 'unapproved']);
        $data = [
            'title' => 'Yêu cầu xin nghỉ ',
            'content' => 'Yêu cầu xin nghỉ của bạn đã bị từ chối ',
            'reason' => $request->content_deny
        ];
        Mail::to($user->email)->send(new LeaveRequestMail($data));
        $user->notify(new LeaveRequestNotification($data));
        Alert::success('Success', 'Request is unapproved. Notification and email send to user')->autoClose(5000);
        return redirect()->route('leave_requests.index');
    }
}

resources/views/timesheet_management/leave_requests/add.blade.php
@section('css_timesheet_management')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw==" crossorigin="anonymous" />
@endsection
@section('title_timesheet_management')
{{__('config.leave_requests_add.title')}}
@endsection
@section('active_listUser','active')
@section('js_timesheet_management')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw==" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/4.15.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#start_at').datetimepicker({
                dateFormat: 'dd/mm/yy',
                timeFormat: 'hh:mm',
                minDate: new Date(),
                value: new Date()
            });
            $('#end_at').datetimepicker({
                dateFormat: 'dd/mm/yy',
                timeFormat: 'hh:mm',
                minDate: new Date(),
                value: new Date()
            });
        });
        CKEDITOR.replace( 'content' );
    </script>
@endsection
@extends('layouts.timesheet_management')
@section('content_timesheet_management')
    <div class="main-content container-fluid">
        <div class="page-title ">
            <h3 class="float-left">{{__('config.leave_requests_add.header')}}</h3>
        </div>
        <br><br><br>
        <section class="section">
            <form id="addUser" class="col-12" action="{{route('leave_requests.store')}}" method="post">
                @csrf
                <div class="row">
                    <div class="col-4">
                        <label for="start_at">{{__('config.leave_requests_add.start_at')}}</label>
                        <input type="text" id="start_at" class="form-control @error('start_at') is-invalid @enderror datetimepicker-input" data-toggle="datetimepicker" data-target="#start_at"
                               name="start_at"
                               value="{{old('start_at')}}">
                        @error('start_at')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="col-4">
                        <label for="end_at">{{__('config.leave_requests_add.end_at')}}</label>
                        <input type="text" id="end_at" class="form-control @error('end_at') is-invalid @enderror datetimepicker-input" data-toggle="datetimepicker" data-target="#end_at"
                               name="end_at"
                               value="{{old('end_at')}}">
                        @error('end_at')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-4">
                        <label for="phone">{{__('config.leave_requests_add.phone')}}</label>
                        <input type="tel" class="form-control @error('phone') is-invalid @enderror" id="phone"
                               name="phone" pattern="^\+?(?:[0-9]??).{9,12}[0-9]$" required
                               value="{{$user->phone??""}}">
                        @error('phone')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-8">
                        <label for="content">{{__('config.leave_requests_add.content')}}</label>
                        <textarea class="form-control @error('content') is-invalid @enderror" aria-label="With textarea" id="content" name="content"></textarea>
                        @error('content')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-3">{{__('config.leave_requests_add.submit')}}</button>
            </form>
        </section>
    </div>
@endsection