routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('change-language');

Auth::routes(['register' => false, 'verify' => false]);

Route::group(['middleware' => 'localization'], function () {
    Route::prefix('')->group(function () {
        Route::get('/', [
            'as' => 'user_check.index',
            'uses' => 'UserCheckController@index',
        ]);
        Route::post('/checkin', [
            'as' => 'user_check.checkin',
            'uses' => 'UserCheckController@checkin',
        ]);
        Route::post('/checkout', [
            'as' => 'user_check.checkout',
            'uses' => 'UserCheckController@checkout',
        ]);
        Route::post('/notify', [
            'as' => 'notify.send',
            'uses' => 'NotificationController@index',
        ]);
        Route::get('/person', [
            'as' => 'person.personList',
            'uses' => 'ListCheckController@personList',
        ]);
        Route::get('/addProblem', [
            'as' => 'person.addProblem',
            'uses' => 'ListCheckController@addProblem',
        ]);
        Route::post('/storeProblem', [
            'as' => 'person.storeProblem',
            'uses' => 'ListCheckController@storeProblem',
        ]);
        Route::get('/people', [
            'as' => 'people.peopleList',
            'uses' => 'ListCheckController@peopleList',
        ]);
        Route::get('/updateCheckOut/{id}', [
            'as' => 'people.updateCheckOut',
            'uses' => 'ListCheckController@updateCheckOut',
        ]);
        Route::get('/updateCheckOut/{id}', [
            'as' => 'people.updateCheckOut',
            'uses' => 'ListCheckController@updateCheckOut',
        ]);
        Route::get('/viewCheck', [
            'as' => 'people.viewCheck',
            'uses' => 'ListCheckController@viewCheck',
        ]);
        Route::post('/storeCheck', [
            'as' => 'people.storeCheck',
            'uses' => 'ListCheckController@storeCheck',
        ]);
    });

    Route::prefix('/statistic')->group(function () {
        Route::get('/', [
            'as' => 'statistic.index',
            'uses' => 'StatisticController@index',
        ]);
        Route::get('/view/{id}/{year}/{month}', [
            'as' => 'statistic.view',
            'uses' => 'StatisticController@view',
        ]);
        Route::post('getMonth/{year}', [
            'as' => 'statistic.getMonth',
            'uses' => 'StatisticController@getMonth',
        ]);
        Route::post('getData/{year}/{month}', [
            'as' => 'statistic.getData',
            'uses' => 'StatisticController@getData',
        ]);
    });

    Route::prefix('/users')->group(function () {
        Route::get('/', [
            'as' => 'users.index',
            'uses' => 'UserController@index',
            'middleware' => 'can:user-view'
        ]);
        Route::get('/add', [
            'as' => 'users.add',
            'uses' => 'UserController@add',
            'middleware' => 'can:user-create'
        ]);
        Route::post('/create', [
            'as' => 'users.create',
            'uses' => 'UserController@create',
            'middleware' => 'can:user-create'
        ]);
        Route::get('/edit/{id}', [
            'as' => 'users.edit',
            'uses' => 'UserController@edit',
            'middleware' => 'can:user-update'
        ]);
        Route::post('/update/{id}', [
            'as' => 'users.update',
            'uses' => 'UserController@update',
            'middleware' => 'can:user-update'
        ]);
        Route::post('/delete/{id}', [
            'as' => 'users.delete',
            'uses' => 'UserController@delete',
            'middleware' => 'can:user-delete'
        ]);
        Route::get('/info', [
            'as' => 'users.info',
            'uses' => 'UserController@info',
        ]);
        Route::get('/editInfo/{id}', [
            'as' => 'users.editInfo',
            'uses' => 'UserController@editInfo',
        ]);
        Route::post('/updateInfo/{id}', [
            'as' => 'users.updateInfo',
            'uses' => 'UserController@updateInfo',
        ]);
    });

    Route::resource('leave_requests', 'LeaveRequestController')->only([
        'index', 'create', 'store',
    ]);
    Route::get('change-password', 'Auth\ChangePasswordController@index');
    Route::post('change-password', 'Auth\ChangePasswordController@store')->name('change.password');
    Route::post('leave_requests/deny/{id}', 'LeaveRequestController@deny')->name('leave_requests.deny');
    Route::get('leave_requests/accept/{id}', 'LeaveRequestController@accept')->name('leave_requests.accept');
    Route::get('change-language/{language}', 'HomeController@changeLanguage')->name('change-language');
});

resources/views/partial/footer.blade.php
<footer>
    <div class="footer clearfix mb-0 text-muted mt-5">
        <div class="float-left">
            <p>2020 &copy;</p>
        </div>
        <div class="float-right">
            <p>Duc<span class='text-danger'><i data-feather="heart"></i></span> by <a href="http://ahmadsaugi.com"></a></p>
        </div>
    </div>
</footer>

resources/views/partial/header.blade.php
<nav class="navbar navbar-header navbar-expand navbar-light">
    <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>
    <button class="btn navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">
            <li class="dropdown nav-icon">
                <a href="#" data-toggle="dropdown" class="nav-link  dropdown-toggle nav-link-lg nav-link-user">
                    <div class="d-lg-inline-block">
                        <i data-feather="bell"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-large">
                    <h5 class='py-2 px-4 font-bold'>{{__('header.notification')}}</h5>
                    <ul class="list-group rounded-none" id="notification">
                    </ul>
                </div>
            </li>
            <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                    <div class="avatar mr-1">
                        <img src="{{asset(\Illuminate\Support\Facades\Auth::user()->profile_image??'admin/assets/images/avatar.png')}}" alt="" srcset="">
                    </div>
                    <div class="d-none d-md-block d-lg-inline-block">{{ __('header.welcome',['Name' => \Illuminate\Support\Facades\Auth::user()->getFullNameAttribute()])}}</div>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{route('users.info')}}"><i data-feather="user"></i>{{ __('header.info')}}</a>
                    <a class="dropdown-item" href="{{url('change-password')}}"><i data-feather="edit-2"></i>{{ __('header.change_password')}}</a>
                    <div class="dropdown-divider">
                    </div>
                    <a class="dropdown-item" href="#" id="logout"><i data-feather="log-out"></i>{{__('header.logout')}}</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
            @php $locale = Session::get('language');
            @endphp
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="dropdown-toggle" href="#" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    @switch($locale)
                        @case('en')
                        <img src="{{asset('img/en.png')}}" alt="" width="40px" height="25px"> English
                        @break
                        @case('vi')
                        <img src="{{asset('img/vn.png')}}" alt="" width="40px" height="25px"> Vietnamese
                        @break
                        @default
                        <img src="{{asset('img/en.png')}}" alt="" width="40px" height="25px"> English
                    @endswitch
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item bg-gray" href="{!! route('change-language', ['en']) !!}"><img src="{{asset('img/en.png')}}" alt="" width="40px" height="25px"> English</a>
                    <a class="dropdown-item bg-gray" href="{!! route('change-language', ['vi']) !!}"><img src="{{asset('img/vn.png')}}" alt="" width="40px" height="25px">VietNamese</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/partial/sidebar.blade.php
<div id="sidebar" class='active'>
    <div class="sidebar-wrapper active">
        <div class="sidebar-header">
            <img src="{{asset('admin/assets/images/logo.png')}}" alt="" srcset="">
        </div>
        <div class="sidebar-menu">
            <ul class="menu">
                <li class="sidebar-item @yield('active_home')">
                    <a href="{{route('user_check.index')}}" class='sidebar-link'>
                        <i data-feather="home" width="20"></i>
                        <span>{{__('sidebar.calendar')}}</span>
                    </a>
                </li>
                @can('isAdmin')
                    <li class="sidebar-item  has-sub @yield('active_history')">
                        <a href="{{route('person.personList')}}" class='sidebar-link'>
                            <i data-feather="triangle" width="20"></i>
                            <span>{{__('sidebar.historyTimeSheet')}}</span>
                        </a>
                        <ul class="submenu">
                            <li>
                                <a href="{{route('person.personList')}}">{{__('sidebar.person')}}</a>
                            </li>
                            <li>
                                <a href="{{route('people.peopleList')}}">{{__('sidebar.people')}}</a>
                            </li>
                        </ul>
                    </li>
                @endcan
                @can('isStaff')
                    <li class="sidebar-item @yield('active_history')">
                        <a href="{{route('person.personList')}}" class='sidebar-link'>
                            <i data-feather="triangle" width="20"></i>
                            <span>{{__('sidebar.historyTimeSheet')}}</span>
                        </a>
                    </li>
                @endcan
                @can('isAdmin')
                    <li class="sidebar-item @yield('active_leaveRequest')">
                        <a href="{{route('leave_requests.index')}}" class='sidebar-link'>
                            <i data-feather="layers" width="20"></i>
                            <span>{{__('sidebar.list_request')}}</span>
                        </a>
                    </li>
                @endcan
                @can('isStaff')
                    <li class="sidebar-item @yield('active_leaveRequest')">
                        <a href="{{route('leave_requests.index')}}" class='sidebar-link'>
                            <i data-feather="layers" width="20"></i>
                            <span>{{__('sidebar.list_request_off')}}</span>
                        </a>
                    </li>
                @endcan
                <li class="sidebar-item  @yield('active_static')">
                    <a href="{{route('statistic.index')}}" class='sidebar-link'>
                        <i data-feather="grid" width="20"></i>
                        <span>{{__('sidebar.statistic')}}</span>
                    </a>
                </li>
                @can('isAdmin')
                    <li class="sidebar-item  @yield('active_listUser')">
                        <a href="{{route('users.index')}}" class='sidebar-link'>
                            <i data-feather="file-plus" width="20"></i>
                            <span>{{__('sidebar.list_user')}}</span>
                        </a>
                    </li>
                @endcan
            </ul>
        </div>
        <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
    </div>
</div>